language: ja

reviews:
  # レビューのトーン
  tone: polite
  high_level_summary: true
  review_status: true

  # コメントの粒度
  comment_level: detailed

  # テストコードもレビュー対象にする
  include_tests: true

  # 重要度の低い指摘を減らす
  ignore:
    - "**/*.Designer.cs"
    - "**/bin/**"
    - "**/obj/**"

  # 個人開発向けにノイズを抑える
  auto_review:
    enabled: true
    drafts: false

  guidelines:
    # テストに関する観点を強調
    - テストは Arrange / Act / Assert の構造が明確か
    - テスト名から仕様が読み取れるか
    - 境界条件や異常系が考慮されているか
    - 実装詳細に依存しすぎていないか

    # アルゴリズム系
    - ループ条件や境界判定に off-by-one の可能性はないか
    - 可読性を下げる最適化が行われていないか

    # C# 向け
    - null / 範囲外アクセスの可能性がないか
    - public API の振る舞いがテストで保証されているか
